# Generated by Django 3.2.2 on 2021-05-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210514_1432'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='official',
            managers=[
            ],
        ),
    ]
